// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: TableSchedule.proto

package schedulepb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_pingcap_tiflow_cdc_model "github.com/pingcap/tiflow/cdc/model"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TableState int32

const (
	TableState_Unknown  TableState = 0
	TableState_Running  TableState = 1
	TableState_Adding   TableState = 2
	TableState_Removing TableState = 3
)

var TableState_name = map[int32]string{
	0: "Unknown",
	1: "Running",
	2: "Adding",
	3: "Removing",
}

var TableState_value = map[string]int32{
	"Unknown":  0,
	"Running":  1,
	"Adding":   2,
	"Removing": 3,
}

func (x TableState) String() string {
	return proto.EnumName(TableState_name, int32(x))
}

func (TableState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{0}
}

type OwnerReversion struct {
	Reversion int64 `protobuf:"varint,1,opt,name=reversion,proto3" json:"reversion,omitempty"`
}

func (m *OwnerReversion) Reset()         { *m = OwnerReversion{} }
func (m *OwnerReversion) String() string { return proto.CompactTextString(m) }
func (*OwnerReversion) ProtoMessage()    {}
func (*OwnerReversion) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{0}
}
func (m *OwnerReversion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OwnerReversion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OwnerReversion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OwnerReversion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerReversion.Merge(m, src)
}
func (m *OwnerReversion) XXX_Size() int {
	return m.Size()
}
func (m *OwnerReversion) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerReversion.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerReversion proto.InternalMessageInfo

func (m *OwnerReversion) GetReversion() int64 {
	if m != nil {
		return m.Reversion
	}
	return 0
}

type ProcessorEpoch struct {
	Epoch string `protobuf:"bytes,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *ProcessorEpoch) Reset()         { *m = ProcessorEpoch{} }
func (m *ProcessorEpoch) String() string { return proto.CompactTextString(m) }
func (*ProcessorEpoch) ProtoMessage()    {}
func (*ProcessorEpoch) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{1}
}
func (m *ProcessorEpoch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProcessorEpoch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProcessorEpoch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProcessorEpoch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorEpoch.Merge(m, src)
}
func (m *ProcessorEpoch) XXX_Size() int {
	return m.Size()
}
func (m *ProcessorEpoch) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorEpoch.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorEpoch proto.InternalMessageInfo

func (m *ProcessorEpoch) GetEpoch() string {
	if m != nil {
		return m.Epoch
	}
	return ""
}

type Checkpoint struct {
	CheckpointTs github_com_pingcap_tiflow_cdc_model.Ts `protobuf:"varint,1,opt,name=checkpoint_ts,json=checkpointTs,proto3,casttype=github.com/pingcap/tiflow/cdc/model.Ts" json:"checkpoint_ts,omitempty"`
	ResolvedTs   github_com_pingcap_tiflow_cdc_model.Ts `protobuf:"varint,2,opt,name=resolved_ts,json=resolvedTs,proto3,casttype=github.com/pingcap/tiflow/cdc/model.Ts" json:"resolved_ts,omitempty"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{2}
}
func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return m.Size()
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetCheckpointTs() github_com_pingcap_tiflow_cdc_model.Ts {
	if m != nil {
		return m.CheckpointTs
	}
	return 0
}

func (m *Checkpoint) GetResolvedTs() github_com_pingcap_tiflow_cdc_model.Ts {
	if m != nil {
		return m.ResolvedTs
	}
	return 0
}

type AddTableRequest struct {
	TableId     github_com_pingcap_tiflow_cdc_model.TableID `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3,casttype=github.com/pingcap/tiflow/cdc/model.TableID" json:"table_id,omitempty"`
	IsSecondary bool                                        `protobuf:"varint,2,opt,name=is_secondary,json=isSecondary,proto3" json:"is_secondary,omitempty"`
	Checkpoint  *Checkpoint                                 `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
}

func (m *AddTableRequest) Reset()         { *m = AddTableRequest{} }
func (m *AddTableRequest) String() string { return proto.CompactTextString(m) }
func (*AddTableRequest) ProtoMessage()    {}
func (*AddTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{3}
}
func (m *AddTableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddTableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTableRequest.Merge(m, src)
}
func (m *AddTableRequest) XXX_Size() int {
	return m.Size()
}
func (m *AddTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddTableRequest proto.InternalMessageInfo

func (m *AddTableRequest) GetTableId() github_com_pingcap_tiflow_cdc_model.TableID {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *AddTableRequest) GetIsSecondary() bool {
	if m != nil {
		return m.IsSecondary
	}
	return false
}

func (m *AddTableRequest) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type RemoveTableRequest struct {
	TableId github_com_pingcap_tiflow_cdc_model.TableID `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3,casttype=github.com/pingcap/tiflow/cdc/model.TableID" json:"table_id,omitempty"`
}

func (m *RemoveTableRequest) Reset()         { *m = RemoveTableRequest{} }
func (m *RemoveTableRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTableRequest) ProtoMessage()    {}
func (*RemoveTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{4}
}
func (m *RemoveTableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveTableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTableRequest.Merge(m, src)
}
func (m *RemoveTableRequest) XXX_Size() int {
	return m.Size()
}
func (m *RemoveTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTableRequest proto.InternalMessageInfo

func (m *RemoveTableRequest) GetTableId() github_com_pingcap_tiflow_cdc_model.TableID {
	if m != nil {
		return m.TableId
	}
	return 0
}

type DispatchTableRequest struct {
	OwnerReversion *OwnerReversion     `protobuf:"bytes,1,opt,name=owner_reversion,json=ownerReversion,proto3" json:"owner_reversion,omitempty"`
	AddTable       *AddTableRequest    `protobuf:"bytes,2,opt,name=add_table,json=addTable,proto3" json:"add_table,omitempty"`
	RemoveTable    *RemoveTableRequest `protobuf:"bytes,3,opt,name=remove_table,json=removeTable,proto3" json:"remove_table,omitempty"`
}

func (m *DispatchTableRequest) Reset()         { *m = DispatchTableRequest{} }
func (m *DispatchTableRequest) String() string { return proto.CompactTextString(m) }
func (*DispatchTableRequest) ProtoMessage()    {}
func (*DispatchTableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{5}
}
func (m *DispatchTableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DispatchTableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DispatchTableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DispatchTableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchTableRequest.Merge(m, src)
}
func (m *DispatchTableRequest) XXX_Size() int {
	return m.Size()
}
func (m *DispatchTableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchTableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchTableRequest proto.InternalMessageInfo

func (m *DispatchTableRequest) GetOwnerReversion() *OwnerReversion {
	if m != nil {
		return m.OwnerReversion
	}
	return nil
}

func (m *DispatchTableRequest) GetAddTable() *AddTableRequest {
	if m != nil {
		return m.AddTable
	}
	return nil
}

func (m *DispatchTableRequest) GetRemoveTable() *RemoveTableRequest {
	if m != nil {
		return m.RemoveTable
	}
	return nil
}

type AddTableResponse struct {
	TableId     github_com_pingcap_tiflow_cdc_model.TableID `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3,casttype=github.com/pingcap/tiflow/cdc/model.TableID" json:"table_id,omitempty"`
	IsSecondary bool                                        `protobuf:"varint,2,opt,name=is_secondary,json=isSecondary,proto3" json:"is_secondary,omitempty"`
	Checkpoint  *Checkpoint                                 `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	Reject      bool                                        `protobuf:"varint,4,opt,name=reject,proto3" json:"reject,omitempty"`
}

func (m *AddTableResponse) Reset()         { *m = AddTableResponse{} }
func (m *AddTableResponse) String() string { return proto.CompactTextString(m) }
func (*AddTableResponse) ProtoMessage()    {}
func (*AddTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{6}
}
func (m *AddTableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddTableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddTableResponse.Merge(m, src)
}
func (m *AddTableResponse) XXX_Size() int {
	return m.Size()
}
func (m *AddTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddTableResponse proto.InternalMessageInfo

func (m *AddTableResponse) GetTableId() github_com_pingcap_tiflow_cdc_model.TableID {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *AddTableResponse) GetIsSecondary() bool {
	if m != nil {
		return m.IsSecondary
	}
	return false
}

func (m *AddTableResponse) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

func (m *AddTableResponse) GetReject() bool {
	if m != nil {
		return m.Reject
	}
	return false
}

type RemoveTableResponse struct {
	TableId    github_com_pingcap_tiflow_cdc_model.TableID `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3,casttype=github.com/pingcap/tiflow/cdc/model.TableID" json:"table_id,omitempty"`
	Checkpoint *Checkpoint                                 `protobuf:"bytes,2,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
}

func (m *RemoveTableResponse) Reset()         { *m = RemoveTableResponse{} }
func (m *RemoveTableResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTableResponse) ProtoMessage()    {}
func (*RemoveTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{7}
}
func (m *RemoveTableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveTableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTableResponse.Merge(m, src)
}
func (m *RemoveTableResponse) XXX_Size() int {
	return m.Size()
}
func (m *RemoveTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTableResponse proto.InternalMessageInfo

func (m *RemoveTableResponse) GetTableId() github_com_pingcap_tiflow_cdc_model.TableID {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *RemoveTableResponse) GetCheckpoint() *Checkpoint {
	if m != nil {
		return m.Checkpoint
	}
	return nil
}

type DispatchTableResponse struct {
	OwnerReversion *OwnerReversion      `protobuf:"bytes,1,opt,name=owner_reversion,json=ownerReversion,proto3" json:"owner_reversion,omitempty"`
	AddTable       *AddTableResponse    `protobuf:"bytes,2,opt,name=add_table,json=addTable,proto3" json:"add_table,omitempty"`
	RemoveTable    *RemoveTableResponse `protobuf:"bytes,3,opt,name=remove_table,json=removeTable,proto3" json:"remove_table,omitempty"`
}

func (m *DispatchTableResponse) Reset()         { *m = DispatchTableResponse{} }
func (m *DispatchTableResponse) String() string { return proto.CompactTextString(m) }
func (*DispatchTableResponse) ProtoMessage()    {}
func (*DispatchTableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{8}
}
func (m *DispatchTableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DispatchTableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DispatchTableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DispatchTableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DispatchTableResponse.Merge(m, src)
}
func (m *DispatchTableResponse) XXX_Size() int {
	return m.Size()
}
func (m *DispatchTableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DispatchTableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DispatchTableResponse proto.InternalMessageInfo

func (m *DispatchTableResponse) GetOwnerReversion() *OwnerReversion {
	if m != nil {
		return m.OwnerReversion
	}
	return nil
}

func (m *DispatchTableResponse) GetAddTable() *AddTableResponse {
	if m != nil {
		return m.AddTable
	}
	return nil
}

func (m *DispatchTableResponse) GetRemoveTable() *RemoveTableResponse {
	if m != nil {
		return m.RemoveTable
	}
	return nil
}

type Announce struct {
	OwnerReversion *OwnerReversion `protobuf:"bytes,1,opt,name=owner_reversion,json=ownerReversion,proto3" json:"owner_reversion,omitempty"`
	OwnerVersion   string          `protobuf:"bytes,2,opt,name=owner_version,json=ownerVersion,proto3" json:"owner_version,omitempty"`
}

func (m *Announce) Reset()         { *m = Announce{} }
func (m *Announce) String() string { return proto.CompactTextString(m) }
func (*Announce) ProtoMessage()    {}
func (*Announce) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{9}
}
func (m *Announce) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Announce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Announce.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Announce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Announce.Merge(m, src)
}
func (m *Announce) XXX_Size() int {
	return m.Size()
}
func (m *Announce) XXX_DiscardUnknown() {
	xxx_messageInfo_Announce.DiscardUnknown(m)
}

var xxx_messageInfo_Announce proto.InternalMessageInfo

func (m *Announce) GetOwnerReversion() *OwnerReversion {
	if m != nil {
		return m.OwnerReversion
	}
	return nil
}

func (m *Announce) GetOwnerVersion() string {
	if m != nil {
		return m.OwnerVersion
	}
	return ""
}

type TableStatus struct {
	TableId github_com_pingcap_tiflow_cdc_model.TableID `protobuf:"varint,1,opt,name=table_id,json=tableId,proto3,casttype=github.com/pingcap/tiflow/cdc/model.TableID" json:"table_id,omitempty"`
	State   TableState                                  `protobuf:"varint,2,opt,name=state,proto3,enum=pingcap.tiflow.cdc.schedulepb.TableState" json:"state,omitempty"`
}

func (m *TableStatus) Reset()         { *m = TableStatus{} }
func (m *TableStatus) String() string { return proto.CompactTextString(m) }
func (*TableStatus) ProtoMessage()    {}
func (*TableStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{10}
}
func (m *TableStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TableStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TableStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TableStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TableStatus.Merge(m, src)
}
func (m *TableStatus) XXX_Size() int {
	return m.Size()
}
func (m *TableStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TableStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TableStatus proto.InternalMessageInfo

func (m *TableStatus) GetTableId() github_com_pingcap_tiflow_cdc_model.TableID {
	if m != nil {
		return m.TableId
	}
	return 0
}

func (m *TableStatus) GetState() TableState {
	if m != nil {
		return m.State
	}
	return TableState_Unknown
}

type Sync struct {
	ProcessorEpoch   *ProcessorEpoch `protobuf:"bytes,1,opt,name=processor_epoch,json=processorEpoch,proto3" json:"processor_epoch,omitempty"`
	ProcessorVersion string          `protobuf:"bytes,2,opt,name=processor_version,json=processorVersion,proto3" json:"processor_version,omitempty"`
}

func (m *Sync) Reset()         { *m = Sync{} }
func (m *Sync) String() string { return proto.CompactTextString(m) }
func (*Sync) ProtoMessage()    {}
func (*Sync) Descriptor() ([]byte, []int) {
	return fileDescriptor_5b343da219629f69, []int{11}
}
func (m *Sync) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Sync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Sync.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Sync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sync.Merge(m, src)
}
func (m *Sync) XXX_Size() int {
	return m.Size()
}
func (m *Sync) XXX_DiscardUnknown() {
	xxx_messageInfo_Sync.DiscardUnknown(m)
}

var xxx_messageInfo_Sync proto.InternalMessageInfo

func (m *Sync) GetProcessorEpoch() *ProcessorEpoch {
	if m != nil {
		return m.ProcessorEpoch
	}
	return nil
}

func (m *Sync) GetProcessorVersion() string {
	if m != nil {
		return m.ProcessorVersion
	}
	return ""
}

func init() {
	proto.RegisterEnum("pingcap.tiflow.cdc.schedulepb.TableState", TableState_name, TableState_value)
	proto.RegisterType((*OwnerReversion)(nil), "pingcap.tiflow.cdc.schedulepb.OwnerReversion")
	proto.RegisterType((*ProcessorEpoch)(nil), "pingcap.tiflow.cdc.schedulepb.ProcessorEpoch")
	proto.RegisterType((*Checkpoint)(nil), "pingcap.tiflow.cdc.schedulepb.Checkpoint")
	proto.RegisterType((*AddTableRequest)(nil), "pingcap.tiflow.cdc.schedulepb.AddTableRequest")
	proto.RegisterType((*RemoveTableRequest)(nil), "pingcap.tiflow.cdc.schedulepb.RemoveTableRequest")
	proto.RegisterType((*DispatchTableRequest)(nil), "pingcap.tiflow.cdc.schedulepb.DispatchTableRequest")
	proto.RegisterType((*AddTableResponse)(nil), "pingcap.tiflow.cdc.schedulepb.AddTableResponse")
	proto.RegisterType((*RemoveTableResponse)(nil), "pingcap.tiflow.cdc.schedulepb.RemoveTableResponse")
	proto.RegisterType((*DispatchTableResponse)(nil), "pingcap.tiflow.cdc.schedulepb.DispatchTableResponse")
	proto.RegisterType((*Announce)(nil), "pingcap.tiflow.cdc.schedulepb.Announce")
	proto.RegisterType((*TableStatus)(nil), "pingcap.tiflow.cdc.schedulepb.TableStatus")
	proto.RegisterType((*Sync)(nil), "pingcap.tiflow.cdc.schedulepb.Sync")
}

func init() { proto.RegisterFile("TableSchedule.proto", fileDescriptor_5b343da219629f69) }

var fileDescriptor_5b343da219629f69 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x96, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0x3b, 0xe5, 0x5f, 0x79, 0xb7, 0x94, 0x3a, 0xa0, 0x21, 0x46, 0x0b, 0xae, 0x86, 0x20,
	0xc4, 0xdd, 0x58, 0x3f, 0x80, 0x82, 0x78, 0x40, 0x4c, 0x30, 0x43, 0xe1, 0xe0, 0xa5, 0x6e, 0x67,
	0xc6, 0x76, 0xa5, 0xcc, 0xac, 0x3b, 0x53, 0x08, 0x9f, 0xc0, 0x83, 0x17, 0x4d, 0x3c, 0xf9, 0x11,
	0x8c, 0x1f, 0xc4, 0xc4, 0x0b, 0x47, 0x4f, 0xc4, 0x80, 0x9f, 0x82, 0x93, 0xd9, 0xd9, 0x2d, 0xcb,
	0x82, 0xb1, 0x10, 0xed, 0xc1, 0xdb, 0xbc, 0xd3, 0x79, 0x9f, 0x79, 0xdf, 0x67, 0x7e, 0xcd, 0xbb,
	0x30, 0x51, 0xf3, 0x1a, 0x6d, 0xbe, 0x4e, 0x5b, 0x9c, 0x75, 0xda, 0xdc, 0x09, 0x42, 0xa9, 0x25,
	0xbe, 0x19, 0xf8, 0xa2, 0x49, 0xbd, 0xc0, 0xd1, 0xfe, 0xab, 0xb6, 0xdc, 0x75, 0x28, 0xa3, 0x8e,
	0x4a, 0x8e, 0x04, 0x8d, 0xeb, 0x93, 0x4d, 0xd9, 0x94, 0xe6, 0xa4, 0x1b, 0xad, 0xe2, 0x24, 0xdb,
	0x81, 0xd2, 0xda, 0xae, 0xe0, 0x21, 0xe1, 0x3b, 0x3c, 0x54, 0xbe, 0x14, 0xf8, 0x06, 0x8c, 0x86,
	0xdd, 0x60, 0x0a, 0xcd, 0xa0, 0xb9, 0x01, 0x92, 0x6e, 0xd8, 0xb3, 0x50, 0x7a, 0x1e, 0x4a, 0xca,
	0x95, 0x92, 0xe1, 0x93, 0x40, 0xd2, 0x16, 0x9e, 0x84, 0x21, 0x1e, 0x2d, 0xcc, 0xd9, 0x51, 0x12,
	0x07, 0xf6, 0x67, 0x04, 0xf0, 0xb8, 0xc5, 0xe9, 0x56, 0x20, 0x7d, 0xa1, 0xf1, 0x1a, 0x8c, 0xd1,
	0x93, 0xa8, 0xae, 0x95, 0x39, 0x3c, 0xb8, 0x34, 0x7f, 0x7c, 0x30, 0x3d, 0xdb, 0xf4, 0x75, 0xab,
	0xd3, 0x70, 0xa8, 0xdc, 0x76, 0x93, 0x0e, 0xdc, 0xb8, 0x03, 0x97, 0x32, 0xea, 0x6e, 0x4b, 0xc6,
	0xdb, 0x4e, 0x4d, 0x91, 0x62, 0x2a, 0x50, 0x53, 0x78, 0x15, 0xac, 0x90, 0x2b, 0xd9, 0xde, 0xe1,
	0x2c, 0x92, 0xcb, 0x5f, 0x5a, 0x0e, 0xba, 0xe9, 0x35, 0x65, 0x7f, 0x43, 0x30, 0xbe, 0xc8, 0x98,
	0x31, 0x95, 0xf0, 0x37, 0x1d, 0xae, 0x34, 0x7e, 0x0a, 0x05, 0x1d, 0xc5, 0x75, 0x9f, 0xc5, 0x2e,
	0x2c, 0xb9, 0xc7, 0x07, 0xd3, 0x0b, 0x17, 0x52, 0x8f, 0xf2, 0x56, 0x96, 0xc9, 0x88, 0x11, 0x58,
	0x61, 0xf8, 0x16, 0x14, 0x7d, 0x55, 0x57, 0x9c, 0x4a, 0xc1, 0xbc, 0x70, 0xcf, 0x54, 0x5b, 0x20,
	0x96, 0xaf, 0xd6, 0xbb, 0x5b, 0x78, 0x05, 0x20, 0xed, 0x6f, 0x6a, 0x60, 0x06, 0xcd, 0x59, 0xd5,
	0xbb, 0xce, 0x1f, 0x5f, 0xd4, 0x49, 0xfd, 0x25, 0xa7, 0x92, 0xed, 0x97, 0x80, 0x09, 0xdf, 0x96,
	0x3b, 0xbc, 0x5f, 0xfd, 0xd8, 0x1f, 0xf2, 0x30, 0xb9, 0xec, 0xab, 0xc0, 0xd3, 0xb4, 0x95, 0xb9,
	0x64, 0x13, 0xc6, 0x65, 0x44, 0x53, 0x3d, 0x4b, 0x90, 0x55, 0xbd, 0xd7, 0xa3, 0x95, 0x2c, 0x83,
	0xa4, 0x24, 0xb3, 0x4c, 0xae, 0xc2, 0xa8, 0xc7, 0x58, 0xdd, 0xdc, 0x6f, 0xdc, 0xb3, 0xaa, 0x4e,
	0x0f, 0xc5, 0x33, 0xef, 0x49, 0x0a, 0x5e, 0xb2, 0x81, 0x6b, 0x50, 0x0c, 0x8d, 0x3f, 0x89, 0x5e,
	0x6c, 0xf6, 0xfd, 0x1e, 0x7a, 0xe7, 0x2d, 0x25, 0x56, 0x98, 0xee, 0xd9, 0x3f, 0x11, 0x94, 0xd3,
	0x3b, 0x55, 0x20, 0x85, 0xe2, 0xff, 0x2f, 0x44, 0xf8, 0x1a, 0x0c, 0x87, 0xfc, 0x35, 0xa7, 0x7a,
	0x6a, 0xd0, 0xdc, 0x93, 0x44, 0xf6, 0x17, 0x04, 0x13, 0x19, 0x2b, 0xfa, 0xd0, 0x69, 0xb6, 0x8d,
	0xfc, 0xdf, 0xfc, 0x17, 0x3e, 0xe6, 0xe1, 0xea, 0x19, 0x52, 0x93, 0x82, 0xfb, 0x85, 0xea, 0xb3,
	0xf3, 0xa8, 0xba, 0x17, 0x46, 0x35, 0xae, 0xed, 0x14, 0xab, 0x1b, 0xbf, 0x65, 0xb5, 0x7a, 0x19,
	0x56, 0x13, 0xcd, 0x0c, 0xac, 0x6f, 0x11, 0x14, 0x16, 0x85, 0x90, 0x1d, 0x41, 0xfb, 0xe7, 0xc4,
	0x6d, 0x18, 0x8b, 0x75, 0xbb, 0xaa, 0x79, 0x33, 0x20, 0x8a, 0x66, 0x73, 0x33, 0x99, 0x27, 0x9f,
	0x10, 0x58, 0xf1, 0x30, 0xd3, 0x9e, 0xee, 0xa8, 0x7f, 0xca, 0xd1, 0x43, 0x18, 0x52, 0xda, 0xd3,
	0xf1, 0x33, 0x94, 0x7a, 0x22, 0x74, 0x52, 0x06, 0x27, 0x71, 0x9e, 0xfd, 0x0e, 0xc1, 0xe0, 0xfa,
	0x9e, 0xa0, 0x91, 0x45, 0x41, 0x77, 0xea, 0xd5, 0xd3, 0x69, 0xd7, 0xdb, 0xa2, 0xec, 0xac, 0x24,
	0xa5, 0x20, 0x3b, 0x3b, 0x17, 0xe0, 0x4a, 0xaa, 0x9b, 0xb5, 0xa9, 0x7c, 0xf2, 0x43, 0x62, 0xd5,
	0xfc, 0x23, 0x80, 0xb4, 0x44, 0x6c, 0xc1, 0xc8, 0x86, 0xd8, 0x12, 0x72, 0x57, 0x94, 0x73, 0x51,
	0x40, 0x3a, 0x42, 0xf8, 0xa2, 0x59, 0x46, 0x18, 0x60, 0x78, 0x91, 0xb1, 0x68, 0x9d, 0xc7, 0x45,
	0x28, 0x18, 0x18, 0xa2, 0x68, 0x60, 0xe9, 0xce, 0xd7, 0xc3, 0x0a, 0xda, 0x3f, 0xac, 0xa0, 0x1f,
	0x87, 0x15, 0xf4, 0xfe, 0xa8, 0x92, 0xdb, 0x3f, 0xaa, 0xe4, 0xbe, 0x1f, 0x55, 0x72, 0x2f, 0x20,
	0xad, 0xb9, 0x31, 0x6c, 0xbe, 0x0c, 0x1e, 0xfc, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x21, 0x02,
	0x7a, 0x65, 0x08, 0x00, 0x00,
}

func (m *OwnerReversion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OwnerReversion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OwnerReversion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reversion != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.Reversion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ProcessorEpoch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProcessorEpoch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProcessorEpoch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Epoch) > 0 {
		i -= len(m.Epoch)
		copy(dAtA[i:], m.Epoch)
		i = encodeVarintTableSchedule(dAtA, i, uint64(len(m.Epoch)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Checkpoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Checkpoint) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Checkpoint) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResolvedTs != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.ResolvedTs))
		i--
		dAtA[i] = 0x10
	}
	if m.CheckpointTs != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.CheckpointTs))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AddTableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddTableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddTableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.IsSecondary {
		i--
		if m.IsSecondary {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.TableId != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RemoveTableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveTableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveTableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TableId != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DispatchTableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DispatchTableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DispatchTableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemoveTable != nil {
		{
			size, err := m.RemoveTable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AddTable != nil {
		{
			size, err := m.AddTable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.OwnerReversion != nil {
		{
			size, err := m.OwnerReversion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AddTableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddTableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddTableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reject {
		i--
		if m.Reject {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.IsSecondary {
		i--
		if m.IsSecondary {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.TableId != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RemoveTableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveTableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveTableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Checkpoint != nil {
		{
			size, err := m.Checkpoint.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TableId != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DispatchTableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DispatchTableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DispatchTableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemoveTable != nil {
		{
			size, err := m.RemoveTable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.AddTable != nil {
		{
			size, err := m.AddTable.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.OwnerReversion != nil {
		{
			size, err := m.OwnerReversion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Announce) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Announce) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Announce) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerVersion) > 0 {
		i -= len(m.OwnerVersion)
		copy(dAtA[i:], m.OwnerVersion)
		i = encodeVarintTableSchedule(dAtA, i, uint64(len(m.OwnerVersion)))
		i--
		dAtA[i] = 0x12
	}
	if m.OwnerReversion != nil {
		{
			size, err := m.OwnerReversion.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TableStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TableStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TableStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.State != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.State))
		i--
		dAtA[i] = 0x10
	}
	if m.TableId != 0 {
		i = encodeVarintTableSchedule(dAtA, i, uint64(m.TableId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Sync) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Sync) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Sync) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProcessorVersion) > 0 {
		i -= len(m.ProcessorVersion)
		copy(dAtA[i:], m.ProcessorVersion)
		i = encodeVarintTableSchedule(dAtA, i, uint64(len(m.ProcessorVersion)))
		i--
		dAtA[i] = 0x12
	}
	if m.ProcessorEpoch != nil {
		{
			size, err := m.ProcessorEpoch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTableSchedule(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTableSchedule(dAtA []byte, offset int, v uint64) int {
	offset -= sovTableSchedule(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OwnerReversion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Reversion != 0 {
		n += 1 + sovTableSchedule(uint64(m.Reversion))
	}
	return n
}

func (m *ProcessorEpoch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Epoch)
	if l > 0 {
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *Checkpoint) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CheckpointTs != 0 {
		n += 1 + sovTableSchedule(uint64(m.CheckpointTs))
	}
	if m.ResolvedTs != 0 {
		n += 1 + sovTableSchedule(uint64(m.ResolvedTs))
	}
	return n
}

func (m *AddTableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovTableSchedule(uint64(m.TableId))
	}
	if m.IsSecondary {
		n += 2
	}
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *RemoveTableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovTableSchedule(uint64(m.TableId))
	}
	return n
}

func (m *DispatchTableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OwnerReversion != nil {
		l = m.OwnerReversion.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	if m.AddTable != nil {
		l = m.AddTable.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	if m.RemoveTable != nil {
		l = m.RemoveTable.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *AddTableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovTableSchedule(uint64(m.TableId))
	}
	if m.IsSecondary {
		n += 2
	}
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	if m.Reject {
		n += 2
	}
	return n
}

func (m *RemoveTableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovTableSchedule(uint64(m.TableId))
	}
	if m.Checkpoint != nil {
		l = m.Checkpoint.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *DispatchTableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OwnerReversion != nil {
		l = m.OwnerReversion.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	if m.AddTable != nil {
		l = m.AddTable.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	if m.RemoveTable != nil {
		l = m.RemoveTable.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *Announce) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OwnerReversion != nil {
		l = m.OwnerReversion.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	l = len(m.OwnerVersion)
	if l > 0 {
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func (m *TableStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TableId != 0 {
		n += 1 + sovTableSchedule(uint64(m.TableId))
	}
	if m.State != 0 {
		n += 1 + sovTableSchedule(uint64(m.State))
	}
	return n
}

func (m *Sync) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ProcessorEpoch != nil {
		l = m.ProcessorEpoch.Size()
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	l = len(m.ProcessorVersion)
	if l > 0 {
		n += 1 + l + sovTableSchedule(uint64(l))
	}
	return n
}

func sovTableSchedule(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTableSchedule(x uint64) (n int) {
	return sovTableSchedule(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OwnerReversion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OwnerReversion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OwnerReversion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reversion", wireType)
			}
			m.Reversion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reversion |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProcessorEpoch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProcessorEpoch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProcessorEpoch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Epoch = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Checkpoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Checkpoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Checkpoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CheckpointTs", wireType)
			}
			m.CheckpointTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CheckpointTs |= github_com_pingcap_tiflow_cdc_model.Ts(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedTs", wireType)
			}
			m.ResolvedTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResolvedTs |= github_com_pingcap_tiflow_cdc_model.Ts(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddTableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddTableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddTableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= github_com_pingcap_tiflow_cdc_model.TableID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSecondary", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSecondary = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &Checkpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveTableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveTableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveTableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= github_com_pingcap_tiflow_cdc_model.TableID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DispatchTableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DispatchTableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DispatchTableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerReversion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OwnerReversion == nil {
				m.OwnerReversion = &OwnerReversion{}
			}
			if err := m.OwnerReversion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AddTable == nil {
				m.AddTable = &AddTableRequest{}
			}
			if err := m.AddTable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemoveTable == nil {
				m.RemoveTable = &RemoveTableRequest{}
			}
			if err := m.RemoveTable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddTableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddTableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddTableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= github_com_pingcap_tiflow_cdc_model.TableID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSecondary", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSecondary = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &Checkpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reject", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reject = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveTableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveTableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveTableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= github_com_pingcap_tiflow_cdc_model.TableID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checkpoint", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checkpoint == nil {
				m.Checkpoint = &Checkpoint{}
			}
			if err := m.Checkpoint.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DispatchTableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DispatchTableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DispatchTableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerReversion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OwnerReversion == nil {
				m.OwnerReversion = &OwnerReversion{}
			}
			if err := m.OwnerReversion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AddTable == nil {
				m.AddTable = &AddTableResponse{}
			}
			if err := m.AddTable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoveTable", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemoveTable == nil {
				m.RemoveTable = &RemoveTableResponse{}
			}
			if err := m.RemoveTable.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Announce) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Announce: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Announce: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerReversion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.OwnerReversion == nil {
				m.OwnerReversion = &OwnerReversion{}
			}
			if err := m.OwnerReversion.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TableStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TableStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TableStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TableId", wireType)
			}
			m.TableId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TableId |= github_com_pingcap_tiflow_cdc_model.TableID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			m.State = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.State |= TableState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Sync) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Sync: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Sync: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessorEpoch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProcessorEpoch == nil {
				m.ProcessorEpoch = &ProcessorEpoch{}
			}
			if err := m.ProcessorEpoch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessorVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTableSchedule
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProcessorVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTableSchedule(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTableSchedule
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTableSchedule(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTableSchedule
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTableSchedule
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTableSchedule
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTableSchedule
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTableSchedule
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTableSchedule        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTableSchedule          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTableSchedule = fmt.Errorf("proto: unexpected end of group")
)
